// Generated by dct.sh and extract_dqt.py. DO NOT EDIT.

// Assuming quantization tables are needed for comparison
// use crate::quantization::QuantizationTable;

use std::println;

#[derive(Debug)]
pub struct ReferenceQuantTestData {
    pub source_group: &'static str,
    pub input_filename: &'static str,
    pub input_format: &'static str, // Format of the *original* input
    pub input_data: &'static [u8],  // Bytes of the *original* input file via include_bytes!
    pub cjpegli_distance: f32,
    pub expected_luma_dqt: [u16; 64],
    pub expected_chroma_dqt: [u16; 64],
}

pub const REFERENCE_QUANT_TEST_DATA: &[ReferenceQuantTestData] = &[
    ReferenceQuantTestData {
        source_group: "jxl-chessboard",
        input_filename: "colorful_chessboards.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/jxl/chessboard/colorful_chessboards.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "jxl-blending",
        input_filename: "cropped_traffic_light_frame-2.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/jxl/blending/cropped_traffic_light_frame-2.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "jxl-blending",
        input_filename: "cropped_traffic_light_frame-3.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/jxl/blending/cropped_traffic_light_frame-3.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "jxl-blending",
        input_filename: "cropped_traffic_light_frame-0.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/jxl/blending/cropped_traffic_light_frame-0.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "jxl-blending",
        input_filename: "cropped_traffic_light_frame-1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/jxl/blending/cropped_traffic_light_frame-1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Google-Pixel2XL-16bit_acescg_g1_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Google-Pixel2XL-16bit_acescg_g1_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Sony-DSC-RX1RM2-14bit_srgb8_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Sony-DSC-RX1RM2-14bit_srgb8_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "DJI-FC6310-16bit_709_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/DJI-FC6310-16bit_709_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Sony-DSC-RX1RM2-14bit_709_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Sony-DSC-RX1RM2-14bit_709_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "HUAWEI-EVA-L09-16bit_srgb8_dt.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/HUAWEI-EVA-L09-16bit_srgb8_dt.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Google-Pixel2XL-16bit_srgb8_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Google-Pixel2XL-16bit_srgb8_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Nikon-D300-12bit_2020_g1_dt.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Nikon-D300-12bit_2020_g1_dt.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "DJI-FC6310-16bit_srgb8_v4_krita.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/DJI-FC6310-16bit_srgb8_v4_krita.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "HUAWEI-EVA-L09-16bit_709_g1_dt.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/HUAWEI-EVA-L09-16bit_709_g1_dt.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "raw.pixls",
        input_filename: "Nikon-D300-12bit_srgb8_dt.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/raw.pixls/Nikon-D300-12bit_srgb8_dt.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "Nikon-D3-14bit_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/Nikon-D3-14bit_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "phu1or_alfann24_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/phu1or_alfann24_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "tmshre_riaphotographs_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/tmshre_riaphotographs_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "t0gho7_orlaustral_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/t0gho7_orlaustral_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "q3a0b3_d17ws_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/q3a0b3_d17ws_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "q3a0b3_d17ws_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/q3a0b3_d17ws_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "ra0ed45_alfann24_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/ra0ed45_alfann24_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "cvo9xd_keong_macan_2020_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/cvo9xd_keong_macan_2020_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "ra0ed45_alfann24_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/ra0ed45_alfann24_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "tmshre_riaphotographs_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/tmshre_riaphotographs_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "cvo9xd_keong_macan_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/cvo9xd_keong_macan_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "u76c0g_bliznaca_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/u76c0g_bliznaca_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "a2d1un_nkitzmiller_2020_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/a2d1un_nkitzmiller_2020_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "t0gho7_orlaustral_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/t0gho7_orlaustral_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "vgqcws_vin_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/vgqcws_vin_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "Nikon-D3-14bit_2020_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/Nikon-D3-14bit_2020_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "l1qnb5_nkitzmiller_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/l1qnb5_nkitzmiller_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "a2d1un_nkitzmiller_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/a2d1un_nkitzmiller_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "u76c0g_bliznaca_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/u76c0g_bliznaca_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "l1qnb5_nkitzmiller_2020_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/l1qnb5_nkitzmiller_2020_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "phu1or_alfann24_2020_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/phu1or_alfann24_2020_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-64px",
        input_filename: "vgqcws_vin_709_g1.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/64px/vgqcws_vin_709_g1.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-500px",
        input_filename: "cvo9xd_keong_macan_grayscale.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/500px/cvo9xd_keong_macan_grayscale.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-500px",
        input_filename: "tmshre_riaphotographs_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/500px/tmshre_riaphotographs_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-500px",
        input_filename: "cvo9xd_keong_macan_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/500px/cvo9xd_keong_macan_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-500px",
        input_filename: "u76c0g_bliznaca_srgb8.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/500px/u76c0g_bliznaca_srgb8.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wesaturate-500px",
        input_filename: "tmshre_riaphotographs_alpha.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wesaturate/500px/tmshre_riaphotographs_alpha.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "P3-sRGB-red.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/P3-sRGB-red.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "R2020-sRGB-blue.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/R2020-sRGB-blue.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "P3-sRGB-blue.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/P3-sRGB-blue.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "R2020-sRGB-green.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/R2020-sRGB-green.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "rgb-to-gbr-test.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/rgb-to-gbr-test.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "R2020-sRGB-color-bars.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/R2020-sRGB-color-bars.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "P3-sRGB-green.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/P3-sRGB-green.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "P3-sRGB-color-bars.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/P3-sRGB-color-bars.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "R2020-sRGB-color-ring.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/R2020-sRGB-color-ring.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "R2020-sRGB-red.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/R2020-sRGB-red.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
    ReferenceQuantTestData {
        source_group: "wide-gamut-tests",
        input_filename: "P3-sRGB-color-ring.png",
        input_format: "PNG",
        input_data: include_bytes!("../../reference_dct/testdata/external/wide-gamut-tests/P3-sRGB-color-ring.png"),
        cjpegli_distance: 1.0, 
        expected_luma_dqt:     [
    16, 24, 24, 40, 32, 40, 40, 40,
    40, 40, 48, 40, 40, 40, 48, 48,
    48, 48, 48, 48, 48, 56, 48, 48,
    48, 48, 48, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 56, 56, 64, 64,
    64, 56, 56, 56, 64, 72, 72, 64,
    56, 64, 80, 72, 80, 64, 80, 72,
    72, 80, 88, 72, 88, 72, 72, 64
],
        expected_chroma_dqt:     [
    40, 88, 88, 128, 120, 128, 152, 128,
    128, 152, 152, 192, 152, 192, 152, 240,
    232, 256, 256, 232, 240, 256, 232, 272,
    256, 272, 232, 256, 408, 376, 336, 224,
    224, 336, 376, 408, 296, 1432, 352, 272,
    352, 1432, 296, 344, 352, 208, 208, 352,
    344, 496, 280, 432, 280, 496, 712, 648,
    648, 712, 936, 856, 936, 1232, 1232, 1560
]
    }
,
];

// Example test - implement actual comparison logic here
#[test]
fn test_reference_quantization_tables_exist() {
    assert!(!REFERENCE_QUANT_TEST_DATA.is_empty(), "No reference test data found.");
    for test_case in REFERENCE_QUANT_TEST_DATA {
        println!("Checking reference data for {} (source: {}, distance: {:.1})...",
                    test_case.input_filename, test_case.source_group, test_case.cjpegli_distance);
        assert_eq!(test_case.expected_luma_dqt.len(), 64);
        assert_eq!(test_case.expected_chroma_dqt.len(), 64);
        // Check a few values to ensure they're not all zero
        // Allow tables to be all zero if extraction failed, maybe add a check for filename?
        // assert!(test_case.expected_luma_dqt.iter().any(|&x| x > 0), "Luma table seems empty");
        // assert!(test_case.expected_chroma_dqt.iter().any(|&x| x > 0), "Chroma table seems empty");
    }
}

