// Generated by generate_dct_references.py. DO NOT EDIT.

// use crate::quantization::QuantizationTable; // Assuming not needed directly now

#[derive(Debug)]
pub struct ReferenceQuantTestData {
    pub source_group: &'static str,
    pub input_filename: &'static str,
    pub input_format: &'static str, // Format of the *original* input
    pub input_data: &'static [u8],  // Bytes of the *original* input file via include_bytes!
    pub cjpegli_distance: f32,
    pub cjpegli_output_data: &'static [u8], // Bytes of the cjpegli *output* JPEG file via include_bytes!
    pub expected_luma_dqt: [u16; 64],       // Extracted Luma DQT
    pub expected_chroma1_dqt: Option<[u16; 64]>, // Extracted Chroma DQT (usually ID 1)
    pub expected_chroma2_dqt: Option<[u16; 64]>, // Extracted Chroma DQT (usually ID 2, optional)
}

pub const REFERENCE_QUANT_TEST_DATA: &[ReferenceQuantTestData] = &[];
